name = "endlessbet"
main = "worker.js"
compatibility_date = "2026-09-18"

[[d1_databases]]
binding = "DB"
database_name = "endlessbet-db"
database_id = "f3d7bb29-8cad-4c96-b79e-46ba46082be9"

[vars]
ADMIN_TOKEN = "eb_sec_x7k9p2m4"
BOT_TOKEN = "8514493880:AAHxO0oO2nk7Nj9gqCYST1wT4JVcotkZI5Q"
